# backend/models/schemas.py
# V2 — includes Evidence Strength, Risk fields, Ranking fields

from pydantic import BaseModel, Field
from typing import List, Optional


# ── Protein Target ────────────────────────────────────────────
class ProteinTarget(BaseModel):
    gene_symbol:          str
    protein_name:         str
    ensembl_id:           str
    biotype:              str
    association_score:    float
    function_description: str
    # ── Feature 6: AlphaFold fields ──────────────────────────
    alphafold_plddt:   float = 0.0    # Structural confidence 0.0-1.0
    alphafold_label:   str   = ""     # V.High / High / Medium / Low
    alphafold_color:   str   = ""     # Hex color for UI
    alphafold_source:  str   = ""     # "AlphaFold API" or "curated"


# ── Drug ─────────────────────────────────────────────────────
class FDAAdverseEvent(BaseModel):
    reaction: str
    count:    int


class Drug(BaseModel):
    drug_name:          str
    drug_type:          str
    clinical_phase:     Optional[int]         = None
    mechanism:          str
    description:        str                   = ""
    target_gene:        str
    fda_adverse_events: List[FDAAdverseEvent] = []
    risk_level:         str                   = "Unknown"
    risk_description:   str                   = ""
    # V4 Feature 4
    competition_intel:  Optional["CompetitionIntel"] = None


# ── Research Paper ────────────────────────────────────────────
class ResearchPaper(BaseModel):
    source:         str
    title:          str
    abstract:       str
    summary:        str
    authors:        List[str]     = []
    year:           Optional[int] = None
    citation_count: int           = 0
    paper_id:       str           = ""
    url:            str           = ""


# ── Evidence Strength ─────────────────────────────────────────
class EvidenceStrength(BaseModel):
    evidence_score:       float = 0.0
    evidence_label:       str   = ""
    evidence_color:       str   = ""
    total_papers:         int   = 0
    high_citation_papers: int   = 0
    recent_papers:        int   = 0
    avg_citations:        float = 0.0
    evidence_breakdown:   str   = ""

# ── Decision Summary ──────────────────────────────────────────
class DecisionSummary(BaseModel):
    """
    Top-level actionable recommendation extracted from
    the best-ranked hypothesis. Shown at the top of the UI.
    """
    best_hypothesis:    str   = ""   # Title of top hypothesis
    recommended_drug:   str   = ""   # Drug from top hypothesis
    target_protein:     str   = ""   # Protein from top hypothesis
    target_pathway:     str   = ""   # Biological pathway mentioned
    confidence_score:   float = 0.0  # final_score of best hypothesis
    confidence_label:   str   = ""   # High / Medium-High / Medium
    risk_level:         str   = ""   # High / Medium / Low / Unknown
    risk_color:         str   = ""   # Hex color for UI
    reasoning_summary:  str   = ""   # 2-sentence actionable summary
    suggested_action:   str   = ""   # What to do next
    evidence_basis:     str   = ""   # What evidence supports this
    # ── V4 Feature 2 ──────────────────────────────────────────
    go_no_go: Optional["GoNoGoDecision"] = None

# ── Causal Analysis ───────────────────────────────────────────
class CausalEvidence(BaseModel):
    """A single piece of causal evidence extracted from a paper."""
    text:          str   = ""   # The sentence containing causal language
    causal_verb:   str   = ""   # The verb that signals causation
    source:        str   = ""   # Paper title or ID
    strength:      str   = ""   # "strong" / "moderate" / "weak"


class CausalAnalysis(BaseModel):
    """
    Causal vs correlational classification for a hypothesis.
    Based on language analysis of supporting papers.
    """
    causal_score:       float = 0.0   # 0.0 (correlational) to 1.0 (causal)
    causal_label:       str   = ""    # "Likely Causal" / "Possibly Causal" / "Correlational"
    causal_color:       str   = ""    # Hex color for UI
    causal_evidence:    List[CausalEvidence] = []
    causal_verbs_found: List[str]     = []
    correlation_note:   str   = ""    # What makes it correlational
    causal_chain:       List[str]     = []  # e.g. ["Drug X", "inhibits", "Protein Y", "reduces", "Pathway Z"]
    total_causal_hits:  int   = 0
    total_papers_scanned: int = 0

# ── Validation Suggestion ─────────────────────────────────────
class ValidationSuggestion(BaseModel):
    """
    Suggested experimental validation method for a hypothesis.
    Generated by LLM based on protein, drug, and pathway context.
    """
    validation_type:        str = ""   # "In-vitro" / "In-vivo" / "Clinical"
    validation_color:       str = ""   # Hex color for UI badge
    experiment_title:       str = ""   # Short experiment name
    experiment_description: str = ""   # Detailed protocol description
    required_tools:         List[str] = []   # Equipment/assays needed
    expected_outcome:       str = ""   # What success looks like
    estimated_timeline:     str = ""   # e.g. "3-6 months"
    difficulty:             str = ""   # "Low" / "Medium" / "High"
    difficulty_color:       str = ""   # Hex color

# ── Hypothesis Critique ───────────────────────────────────────
class HypothesisCritique(BaseModel):
    """
    Critical evaluation of a hypothesis.
    Identifies weaknesses, contradictions, and limitations.
    """
    overall_assessment: str       = ""   # 1-sentence verdict
    weaknesses:         List[str] = []   # List of specific weaknesses
    contradictory_evidence: List[str] = []  # Known contradicting studies/facts
    risks:              List[str] = []   # Clinical/scientific risks
    confidence_impact:  str       = ""   # How critique affects confidence
    salvage_suggestion: str       = ""   # How to strengthen the hypothesis
    critique_severity:  str       = ""   # "Minor" / "Moderate" / "Major"
    severity_color:     str       = ""   # Hex color

# ── Uncertainty Analysis ──────────────────────────────────────
class UncertaintyFactor(BaseModel):
    """A single factor contributing to uncertainty."""
    factor:      str   = ""    # What the factor is
    impact:      str   = ""    # "High" / "Medium" / "Low"
    description: str   = ""    # Why it matters


class UncertaintyAnalysis(BaseModel):
    """
    Reliability assessment for a hypothesis or full analysis.
    Measures HOW RELIABLE the confidence score is.

    High confidence + Low uncertainty  = Strong result
    High confidence + High uncertainty = Treat with caution
    """
    uncertainty_score:  float = 0.0   # 0.0 (certain) to 1.0 (uncertain)
    uncertainty_label:  str   = ""    # "Low" / "Medium" / "High" / "Very High"
    uncertainty_color:  str   = ""    # Hex color

    # Contributing factors
    factors:            List[UncertaintyFactor] = []

    # Data quality flags
    low_paper_count:    bool  = False  # <3 papers
    weak_protein_assoc: bool  = False  # top protein score < 0.7
    high_fda_risk:      bool  = False  # any High risk drug
    no_causal_evidence: bool  = False  # causal score < 0.2
    limited_drug_data:  bool  = False  # <2 drugs found

    # Summary
    uncertainty_reason: str   = ""    # Human-readable explanation
    reliability_note:   str   = ""    # What would reduce uncertainty

# ── GO/NO-GO Decision ─────────────────────────────────────────
class GoNoGoDecision(BaseModel):
    """
    Final actionable GO/NO-GO decision for a hypothesis or analysis.
    The single most important output of the entire platform.
    """
    decision:           str   = ""    # "GO" / "NO-GO" / "INVESTIGATE"
    decision_color:     str   = ""    # Hex color
    decision_emoji:     str   = ""    # ✅ / ❌ / 🔍
    confidence_in_decision: float = 0.0  # 0.0–1.0

    # Score components used
    composite_score:    float = 0.0
    uncertainty_score:  float = 0.0
    risk_level:         str   = ""
    evidence_label:     str   = ""

    # Decision reasoning
    primary_reason:     str   = ""    # Main reason for decision
    supporting_reasons: List[str] = []
    blocking_reasons:   List[str] = []  # Why NOT to go

    # What to do next
    recommended_action: str   = ""
    conditions_to_flip: str   = ""    # What would change the decision

# ── Failure Prediction ────────────────────────────────────────
class FailureReason(BaseModel):
    """A specific predicted failure reason."""
    category:    str = ""   # "Safety" / "Efficacy" / "Mechanism" / "Trial"
    reason:      str = ""   # Specific failure reason
    severity:    str = ""   # "High" / "Medium" / "Low"
    evidence:    str = ""   # What supports this prediction
    mitigation:  str = ""   # How to address it


class FailurePrediction(BaseModel):
    """
    Predicts why a hypothesis/drug might fail in development.
    Based on historical failure patterns, safety signals, and
    mechanism strength.
    """
    failure_risk_score:   float = 0.0  # 0.0 (low risk) to 1.0 (high risk)
    failure_risk_label:   str   = ""   # "Low" / "Medium" / "High" / "Very High"
    failure_risk_color:   str   = ""   # Hex color

    failure_reasons:      List[FailureReason] = []
    top_failure_reason:   str   = ""   # Single most likely failure mode
    historical_context:   str   = ""   # Known failures in similar drug class
    success_probability:  float = 0.0  # Estimated probability of success
    recommended_safeguards: List[str] = []

# ── Competition Intelligence ──────────────────────────────────
class CompetitionIntel(BaseModel):
    """
    Market competition analysis for a drug-target combination.
    Helps assess strategic positioning and market opportunity.
    """
    competition_level:   str   = ""    # "Low" / "Medium" / "High"
    competition_color:   str   = ""    # Hex color
    num_similar_drugs:   int   = 0     # Number of drugs in same class
    similar_drug_names:  List[str] = []
    market_opportunity:  str   = ""    # "Strong" / "Moderate" / "Crowded"
    strategic_note:      str   = ""    # 1-sentence positioning note
    drug_class:          str   = ""    # e.g. "Gamma-secretase inhibitor"

# ── Time-to-Impact Prediction ─────────────────────────────────
class TimeToImpact(BaseModel):
    """
    Estimates time from current stage to market/clinical impact.
    Based on clinical phase, risk level, and historical benchmarks.
    """
    years_to_market:        float = 0.0   # Estimated years
    years_range:            str   = ""    # e.g. "3–7 years"
    current_stage:          str   = ""    # e.g. "Phase 4 / FDA Approved"
    next_milestone:         str   = ""    # What needs to happen next
    success_probability:    float = 0.0   # Overall probability to market
    speed_category:         str   = ""    # "Fast" / "Medium" / "Slow"
    speed_color:            str   = ""    # Hex color
    timeline_breakdown:     List[str] = []  # Step-by-step timeline
    key_bottlenecks:        List[str] = []


# ── Executive Summary ─────────────────────────────────────────
class ExecutiveSummary(BaseModel):
    """
    Non-technical 3-4 sentence summary for business stakeholders.
    Answers: what, why it matters, what to do, what the risk is.
    """
    headline:           str = ""   # One punchy sentence
    body:               str = ""   # 3-4 sentence summary
    market_opportunity: str = ""   # Business value statement
    bottom_line:        str = ""   # Single sentence call to action
    audience_level:     str = ""   # "Executive" / "Investor" / "General"


# ── Literature Review ─────────────────────────────────────────
class LiteratureReview(BaseModel):
    """
    Structured research-style literature review report.
    """
    disease_name:       str = ""
    background:         str = ""   # Disease overview
    current_research:   str = ""   # State of the field
    research_gaps:      str = ""   # What's missing
    proposed_hypothesis:str = ""   # The hypothesis explained
    supporting_evidence:str = ""   # Evidence summary
    risks_limitations:  str = ""   # Known risks
    conclusion:         str = ""   # Final assessment
    generated_at:       str = ""   # Timestamp

# ── Multi-Disease Comparison ──────────────────────────────────
class DiseaseComparisonEntry(BaseModel):
    """Score for one drug across one disease."""
    disease_name:    str
    final_score:     float = 0.0
    confidence:      float = 0.0
    risk_level:      str   = "Unknown"
    hypothesis_title:str   = ""


class DrugComparisonRow(BaseModel):
    """One drug compared across multiple diseases."""
    drug_name:       str
    target_protein:  str                      = ""
    mechanism:       str                      = ""
    diseases:        List[DiseaseComparisonEntry] = []
    overlap_score:   float = 0.0   # How consistent across diseases (0-1)
    avg_score:       float = 0.0   # Average final_score across diseases
    appears_in:      int   = 0     # How many diseases this drug appears in


class SharedProtein(BaseModel):
    """A protein appearing in multiple disease analyses."""
    gene_symbol:        str
    protein_name:       str
    diseases:           List[str]  = []
    avg_association:    float      = 0.0
    appears_in:         int        = 0


class MultiDiseaseComparison(BaseModel):
    """Full multi-disease comparison result."""
    diseases_analyzed:  List[str]              = []
    shared_proteins:    List[SharedProtein]    = []
    drug_comparison:    List[DrugComparisonRow]= []
    total_shared_proteins: int                 = 0
    total_shared_drugs:    int                 = 0
    repurposing_opportunities: List[str]       = []


# ── Multi-Disease Request ─────────────────────────────────────
class MultiDiseaseRequest(BaseModel):
    diseases:    List[str] = Field(
        ...,
        min_length=2,
        example=["Alzheimer disease", "Parkinson disease"]
    )
    max_targets: int = Field(default=5, ge=1, le=10)
    max_papers:  int = Field(default=4, ge=1, le=10)
    max_drugs:   int = Field(default=3, ge=1, le=5)


# ── Hypothesis ────────────────────────────────────────────────
class Hypothesis(BaseModel):
    title:              str
    explanation:        str
    simple_explanation: str
    confidence_score:   float
    confidence_label:   str

    # Ranking fields (Feature 1)
    rank:            int   = 0
    final_score:     float = 0.0
    protein_score:   float = 0.0
    drug_score:      float = 0.0
    paper_score:     float = 0.0
    risk_penalty:    float = 0.0
    score_breakdown: str   = ""

    key_proteins:    List[str] = []
    key_drugs:       List[str] = []
    evidence_summary: str      = ""
    reasoning_steps:  List[str] = []

    # ── Feature 3: Causal Analysis ────────────────────────────
    causal_analysis: Optional["CausalAnalysis"] = None

    # Feature 3
    causal_analysis:      Optional["CausalAnalysis"]      = None
    # Feature 4
    validation_suggestion: Optional["ValidationSuggestion"] = None
    # Feature 5
    critique:              Optional["HypothesisCritique"]   = None
    # Feature 5 (V4)
    uncertainty: Optional["UncertaintyAnalysis"] = None
    # V4 Feature 2
    go_no_go:    Optional["GoNoGoDecision"]      = None
    # V4 Feature 3
    failure_prediction: Optional["FailurePrediction"]   = None
    # V4 Features 5-7
    time_to_impact:     Optional["TimeToImpact"]       = None
    executive_summary:  Optional["ExecutiveSummary"]   = None


# ── Full Analysis Result ──────────────────────────────────────
class DiseaseAnalysisResult(BaseModel):
    disease_name:      str
    disease_id:        str                        = ""
    protein_targets:   List[ProteinTarget]        = []
    drugs:             List[Drug]                 = []
    papers:            List[ResearchPaper]        = []
    hypotheses:        List[Hypothesis]           = []
    evidence_strength: Optional[EvidenceStrength] = None
    decision_summary:  Optional[DecisionSummary]  = None
    # V4 Feature 1
    analysis_uncertainty: Optional["UncertaintyAnalysis"] = None
    # V4 Feature 7
    literature_review:  Optional["LiteratureReview"]   = None
    analysis_status:   str                        = "pending"
    error_message:     str                        = ""


# ── API Request / Response ────────────────────────────────────
class AnalysisRequest(BaseModel):
    disease_name: str = Field(
        ...,
        min_length=2,
        max_length=100,
        example="Alzheimer disease"
    )
    max_targets: int = Field(default=5, ge=1, le=10)
    max_papers:  int = Field(default=5, ge=1, le=10)
    max_drugs:   int = Field(default=3, ge=1, le=5)


class AnalysisResponse(BaseModel):
    success: bool
    data:    Optional[DiseaseAnalysisResult] = None
    message: str = ""