# backend/models/schemas.py
# V2 — includes Evidence Strength, Risk fields, Ranking fields

from pydantic import BaseModel, Field
from typing import List, Optional


# ── Protein Target ────────────────────────────────────────────
class ProteinTarget(BaseModel):
    gene_symbol:          str
    protein_name:         str
    ensembl_id:           str
    biotype:              str
    association_score:    float
    function_description: str
    # ── Feature 6: AlphaFold fields ──────────────────────────
    alphafold_plddt:   float = 0.0    # Structural confidence 0.0-1.0
    alphafold_label:   str   = ""     # V.High / High / Medium / Low
    alphafold_color:   str   = ""     # Hex color for UI
    alphafold_source:  str   = ""     # "AlphaFold API" or "curated"


# ── Drug ─────────────────────────────────────────────────────
class FDAAdverseEvent(BaseModel):
    reaction: str
    count:    int


class Drug(BaseModel):
    drug_name:          str
    drug_type:          str
    clinical_phase:     Optional[int]         = None
    mechanism:          str
    description:        str                   = ""
    target_gene:        str
    fda_adverse_events: List[FDAAdverseEvent] = []
    risk_level:         str                   = "Unknown"
    risk_description:   str                   = ""


# ── Research Paper ────────────────────────────────────────────
class ResearchPaper(BaseModel):
    source:         str
    title:          str
    abstract:       str
    summary:        str
    authors:        List[str]     = []
    year:           Optional[int] = None
    citation_count: int           = 0
    paper_id:       str           = ""
    url:            str           = ""


# ── Evidence Strength ─────────────────────────────────────────
class EvidenceStrength(BaseModel):
    evidence_score:       float = 0.0
    evidence_label:       str   = ""
    evidence_color:       str   = ""
    total_papers:         int   = 0
    high_citation_papers: int   = 0
    recent_papers:        int   = 0
    avg_citations:        float = 0.0
    evidence_breakdown:   str   = ""

# ── Decision Summary ──────────────────────────────────────────
class DecisionSummary(BaseModel):
    """
    Top-level actionable recommendation extracted from
    the best-ranked hypothesis. Shown at the top of the UI.
    """
    best_hypothesis:    str   = ""   # Title of top hypothesis
    recommended_drug:   str   = ""   # Drug from top hypothesis
    target_protein:     str   = ""   # Protein from top hypothesis
    target_pathway:     str   = ""   # Biological pathway mentioned
    confidence_score:   float = 0.0  # final_score of best hypothesis
    confidence_label:   str   = ""   # High / Medium-High / Medium
    risk_level:         str   = ""   # High / Medium / Low / Unknown
    risk_color:         str   = ""   # Hex color for UI
    reasoning_summary:  str   = ""   # 2-sentence actionable summary
    suggested_action:   str   = ""   # What to do next
    evidence_basis:     str   = ""   # What evidence supports this

# ── Causal Analysis ───────────────────────────────────────────
class CausalEvidence(BaseModel):
    """A single piece of causal evidence extracted from a paper."""
    text:          str   = ""   # The sentence containing causal language
    causal_verb:   str   = ""   # The verb that signals causation
    source:        str   = ""   # Paper title or ID
    strength:      str   = ""   # "strong" / "moderate" / "weak"


class CausalAnalysis(BaseModel):
    """
    Causal vs correlational classification for a hypothesis.
    Based on language analysis of supporting papers.
    """
    causal_score:       float = 0.0   # 0.0 (correlational) to 1.0 (causal)
    causal_label:       str   = ""    # "Likely Causal" / "Possibly Causal" / "Correlational"
    causal_color:       str   = ""    # Hex color for UI
    causal_evidence:    List[CausalEvidence] = []
    causal_verbs_found: List[str]     = []
    correlation_note:   str   = ""    # What makes it correlational
    causal_chain:       List[str]     = []  # e.g. ["Drug X", "inhibits", "Protein Y", "reduces", "Pathway Z"]
    total_causal_hits:  int   = 0
    total_papers_scanned: int = 0

# ── Validation Suggestion ─────────────────────────────────────
class ValidationSuggestion(BaseModel):
    """
    Suggested experimental validation method for a hypothesis.
    Generated by LLM based on protein, drug, and pathway context.
    """
    validation_type:        str = ""   # "In-vitro" / "In-vivo" / "Clinical"
    validation_color:       str = ""   # Hex color for UI badge
    experiment_title:       str = ""   # Short experiment name
    experiment_description: str = ""   # Detailed protocol description
    required_tools:         List[str] = []   # Equipment/assays needed
    expected_outcome:       str = ""   # What success looks like
    estimated_timeline:     str = ""   # e.g. "3-6 months"
    difficulty:             str = ""   # "Low" / "Medium" / "High"
    difficulty_color:       str = ""   # Hex color

# ── Hypothesis Critique ───────────────────────────────────────
class HypothesisCritique(BaseModel):
    """
    Critical evaluation of a hypothesis.
    Identifies weaknesses, contradictions, and limitations.
    """
    overall_assessment: str       = ""   # 1-sentence verdict
    weaknesses:         List[str] = []   # List of specific weaknesses
    contradictory_evidence: List[str] = []  # Known contradicting studies/facts
    risks:              List[str] = []   # Clinical/scientific risks
    confidence_impact:  str       = ""   # How critique affects confidence
    salvage_suggestion: str       = ""   # How to strengthen the hypothesis
    critique_severity:  str       = ""   # "Minor" / "Moderate" / "Major"
    severity_color:     str       = ""   # Hex color

# ── Multi-Disease Comparison ──────────────────────────────────
class DiseaseComparisonEntry(BaseModel):
    """Score for one drug across one disease."""
    disease_name:    str
    final_score:     float = 0.0
    confidence:      float = 0.0
    risk_level:      str   = "Unknown"
    hypothesis_title:str   = ""


class DrugComparisonRow(BaseModel):
    """One drug compared across multiple diseases."""
    drug_name:       str
    target_protein:  str                      = ""
    mechanism:       str                      = ""
    diseases:        List[DiseaseComparisonEntry] = []
    overlap_score:   float = 0.0   # How consistent across diseases (0-1)
    avg_score:       float = 0.0   # Average final_score across diseases
    appears_in:      int   = 0     # How many diseases this drug appears in


class SharedProtein(BaseModel):
    """A protein appearing in multiple disease analyses."""
    gene_symbol:        str
    protein_name:       str
    diseases:           List[str]  = []
    avg_association:    float      = 0.0
    appears_in:         int        = 0


class MultiDiseaseComparison(BaseModel):
    """Full multi-disease comparison result."""
    diseases_analyzed:  List[str]              = []
    shared_proteins:    List[SharedProtein]    = []
    drug_comparison:    List[DrugComparisonRow]= []
    total_shared_proteins: int                 = 0
    total_shared_drugs:    int                 = 0
    repurposing_opportunities: List[str]       = []


# ── Multi-Disease Request ─────────────────────────────────────
class MultiDiseaseRequest(BaseModel):
    diseases:    List[str] = Field(
        ...,
        min_length=2,
        example=["Alzheimer disease", "Parkinson disease"]
    )
    max_targets: int = Field(default=5, ge=1, le=10)
    max_papers:  int = Field(default=4, ge=1, le=10)
    max_drugs:   int = Field(default=3, ge=1, le=5)


# ── Hypothesis ────────────────────────────────────────────────
class Hypothesis(BaseModel):
    title:              str
    explanation:        str
    simple_explanation: str
    confidence_score:   float
    confidence_label:   str

    # Ranking fields (Feature 1)
    rank:            int   = 0
    final_score:     float = 0.0
    protein_score:   float = 0.0
    drug_score:      float = 0.0
    paper_score:     float = 0.0
    risk_penalty:    float = 0.0
    score_breakdown: str   = ""

    key_proteins:    List[str] = []
    key_drugs:       List[str] = []
    evidence_summary: str      = ""
    reasoning_steps:  List[str] = []

    # ── Feature 3: Causal Analysis ────────────────────────────
    causal_analysis: Optional["CausalAnalysis"] = None

    # Feature 3
    causal_analysis:      Optional["CausalAnalysis"]      = None
    # Feature 4
    validation_suggestion: Optional["ValidationSuggestion"] = None
    # Feature 5
    critique:              Optional["HypothesisCritique"]   = None


# ── Full Analysis Result ──────────────────────────────────────
class DiseaseAnalysisResult(BaseModel):
    disease_name:      str
    disease_id:        str                        = ""
    protein_targets:   List[ProteinTarget]        = []
    drugs:             List[Drug]                 = []
    papers:            List[ResearchPaper]        = []
    hypotheses:        List[Hypothesis]           = []
    evidence_strength: Optional[EvidenceStrength] = None
    decision_summary:  Optional[DecisionSummary]  = None
    analysis_status:   str                        = "pending"
    error_message:     str                        = ""


# ── API Request / Response ────────────────────────────────────
class AnalysisRequest(BaseModel):
    disease_name: str = Field(
        ...,
        min_length=2,
        max_length=100,
        example="Alzheimer disease"
    )
    max_targets: int = Field(default=5, ge=1, le=10)
    max_papers:  int = Field(default=5, ge=1, le=10)
    max_drugs:   int = Field(default=3, ge=1, le=5)


class AnalysisResponse(BaseModel):
    success: bool
    data:    Optional[DiseaseAnalysisResult] = None
    message: str = ""